name: FlyPlugin
version: 1.1
author: Inusara
main: org.inusara.Main
api-version: '1.20.6'
commands:
    fly:
        description: "Enables or disables fly on players."
    flyspeed:
        description: "Changes fly speed."
    lfly:
        description: "Shows list of able to fly."
permissions:
    Fly.permission:
        default: Op